### ISSUE TITLE
Update run_smoke_test.yml with ability to intake user inputs from workflow dispatch 

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [cisagov/ScubaGoggles#340]
# 💡 Summary #

The [run_smoke_test.yml](https://github.com/cisagov/ScubaGoggles/blob/171-functional-smoke-test/.github/workflows/run_smoke_test.yml) workflow runs when pull requests are opened/synchronized and on pushes to main. After the [initial PR](https://github.com/cisagov/ScubaGoggles/pull/336) is merged, we can expand the workflow_dispatch functionality to accommodate user input.

## Motivation and context ##

One drawback with the current implementation is hardcoded values in the workflow. The workflow would be more dynamic if a user can specify comma-delimited values for the os, python version, and opa version for further testing. 

![Screenshot (161)_LI](https://github.com/user-attachments/assets/a52a438f-762a-4ff7-aef4-422b8bcf0282)

## Implementation notes ##

Add inputs under workflow_dispatch, which can be accessed in the workflow with ${{ inputs.name }}. Below is an example from one of ScubaGear's workflows:
```
on:
  workflow_dispatch:
    inputs:
      OverrideModuleVersion:
        description: "Always enter the release version in semantic version format, Major.Minor.Patch (e.g., 1.3.0):"
        required: false
        type: string
      IsPrerelease:
        description: "If pre-release, check here:"
        required: false
        type: boolean
        default: false
```

## Acceptance criteria ##

How do we know when this work is done?

- [ ] run_smoke_test.yml can be run manually with custom user input for os, python/opa versions. Otherwise use default values.
